bgmi/front/http.py
bgmi/utils/utils.py
bgmi/website/base.py

bug fix for bangumi.script cover

---

bgmi/website/mikan.py

ci居然缩短了最多4分钟..原来一共才需要8分钟............
合并完这个pr就开始改admin(x

feat(mikan):parallelize fetching bangumi calendar

---

bgmi/website/share_dmhy.py

fix a url hard coding

---

Dockerfile
README.rst
bgmi/controllers.py
docker.sh
others/supervisord.conf

fix multi bugs

---

bgmi/config.py
bgmi/main.py
bgmi/setup.py

fix bug of #44

---

README.rst
bgmi/__init__.py
bgmi/controllers.py
bgmi/front/base.py
bgmi/front/index.py
bgmi/models.py
bgmi/utils/utils.py
bgmi/website/base.py

cover images will store with domain in path
include COVER_URL in path instead of json response
蛋疼 cnpm同步不过来0.10.x了 要安装需要手动改成npm的域名

unify cover url of bangumi and script

---

.gitignore
.travis.yml
bgmi/cli.py
bgmi/config.py
bgmi/constants.py
bgmi/controllers.py
bgmi/download.py
bgmi/front/resources.py
bgmi/main.py
bgmi/others/_bgmi_completion.sh
bgmi/script.py
bgmi/website/bangumi_moe.py
bgmi/website/base.py
bgmi/website/mikan.py
bgmi/website/share_dmhy.py
codecov.yml

bash的自动补全
usage: `eval "$(bgmi complete)"`
原来的办法太蠢了而且太慢,windows下补全选项末尾还会跟有一个丑陋的`^M`
因为番剧名里面有空格,还没想好怎么弄,暂时没提供补全的功能
所以add delete fetch几个命令暂时还没有补全..
如果要给`python -m bgmi.main`补全的话需要alias成bgmi
或者手动修改一下`bgmi/others/_bgmi_completion.sh`,把最后一行的bgmi改成上面那个.
zsh的还没弄,虽然我也是用zsh多(

bash completion

---

bgmi/website/share_dmhy.py

编码问题再修复 python3也能跑通了

---

.travis.yml
README.rst
bgmi/website/mikan.py
tests/test_controllers.py
tests/test_http_api.py

update ci bangumi and bug fix

---

bgmi/controllers.py
bgmi/models.py
requirements.txt

upgrade dependence peewee to 3.x.x

---

.travis.yml
ci/disable_transmission_auth_require.py
ci/install_and_start_downloader
ci/stop_downloader.py

downloader ci test

---

bgmi/config.py

add global filter

---

.travis.yml
bgmi/lib/update.py
bgmi/main.py
bgmi/script.py
tests/test_controllers.py
tests/test_utils.py
tests/test_website.py

upgrade from bgmi<3.0.0

---

Dockerfile
README.rst

usage: 
```bash
docker build https://github.com/Trim21/BGmi.git#feature/docker-executable -t bgmi
alias bgmi="docker run -v $HOME/.bgmi:/bgmi bgmi"
bgmi cal
```

make docker container executable

---

bgmi/website/__init__.py
requirements.txt

use difflib instead of fuzzywuzzy

---

.travis.yml
README.rst
bgmi/lib/constants/__init__.py
bgmi/main.py

skip download web static files for ci or someone don't need bgmi_http

feat(cli): install --no-web options

---

bgmi/website/bangumi_moe.py

fix no-translated bangumi name 

---

Dockerfile
README.rst
bgmi/config.py
bgmi/lib/controllers.py
bgmi/lib/models/_tables.py
bgmi/script.py

read config section `keyword weight` and convert its value to int
if there is no this section in config file, will add section to config
file.
when updating, torrents list will be sorted by config.KEYWORD_WEIGHT
close #143

feat(download): sort torrents by keyword weight

---

bgmi/__init__.py

release 2.1.3

---

.ci/azure-pipelines.yml
.ci/jobs/lint/mypy.yaml
.ci/jobs/lint/style.yaml
.ci/jobs/test.yaml
.pre-commit-config.yaml
bgmi/downloader/xunlei.py
bgmi/setup.py
bgmi/utils/__init__.py
poetry.lock
pyproject.toml
pytest.ini
tests/test_config.py
tests/test_controllers.py

regular deps update

---

bgmi/website/mikan.py
tests/test_data_source.py

fetch full episode list of mikan source

---

bgmi/lib/controllers.py

fix(update): network error will not break downlad

---

bgmi/utils/__init__.py
tests/test_utils.py

- [Lilith-Raws] 如果究极进化的完全沉浸 RPG 比现实还更像垃圾游戏的话 / Full Dive - 02 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4]
- [Lilith-Raws] 86 - Eighty Six - 01 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4]
希望不会导致什么原本的集数解析错误
close: #261
close: #263

fix: episode parser

---

bgmi/lib/cli.py
bgmi/lib/controllers.py
bgmi/website/base.py

fix: filter function on banugmi.moe

---

bgmi/website/share_dmhy.py

fix: source share.dmhy calendar parse

---

bgmi/lib/cli.py
bgmi/lib/constants.py
bgmi/lib/controllers.py
bgmi/website/bangumi_moe.py
bgmi/website/base.py
bgmi/website/mikan.py
bgmi/website/share_dmhy.py
poetry.lock
pyproject.toml
tests/conftest.py
tests/test_cli.py
tests/test_data_source.py

Add `--tag` option and `--subtitle` argument in search command.
It will search for precise anime and subtitle group as provided in args in bangumi and mikan. It is useful when trying to download a complete anime collection from the previous season.
We can directly search for subtitle groups in bangumi_moe, but not the mikan. So after fetching the anime pages in mikan, we use Levenshtein distance to compare against the query if provided, otherwise, we use the result from the first subtitle group.
Example:
```shell
bgmi search --tag "明日同学" --subtitle "Loli"
```
Result:
bangumi:
```
$ BGMI_PATH=`pwd`/dist p -m bgmi search --tag "孤独摇滚" --subtitle "Loli"
[*] Matched anime: ぼっち・ざ・ろっく！ (632762d92eaf6e578875f80a)
[*] Matched subtitle: LoliHouse (581be821ee98e9ca20730eae)
[+] [动漫国字幕组&LoliHouse] …
```

Support precise search by anime tag and subtitle group tag in bangumi and mikan

---

poetry.lock
pyproject.toml

Revert "build(deps): pin dependencies"

---

README.cn.md
README.md
bgmi/config.py

config: generate default config from env

---

README.md
bgmi/main.py

feat: `config set` command to update command

---

bgmi/front/resources.py
bgmi/lib/controllers.py
bgmi/lib/download.py
bgmi/lib/models.py
bgmi/lib/update.py
bgmi/script.py

- Download model 增加 created_time 字段
- download hook 增加相关参数
- download TODO 日历 `/resource/calendar.ics?type=download`

feat: add `created_time` to download table and add router `/resource/calendar.ics?type=download`
